
# This is a basic workflow to help you get started with Actions

name: CI

# COUCOU !!

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v3
      
      # Get Node.JS
      - name: Use Node.JS
        uses: actions/setup-node@v3 
        with:  
          node-version: '16.17.1'
          cache: npm
          
      - name: Install dependencies
        run: npm install
        
      # Run Unit Test
      - name: Unit Test
        run: |
          npm run test-headless
      
      # Build project
      - name: Build project 
        run: npm run build:prod
        
      # Deploy Requirements:
      #- name: Install Deploy Requirement
      #  run: npm run deploy-requirement 
      

      - name: Deploy
        if: github.event.pull_request.merged == true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/hello-world/
          enable_jekyll: true
 
        
      # Deploy Project
      #- name: Deploy Project
      #  run: npm run deploy
        
      # Upload an artefact to
      #- name: Upload artifact  
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: lollipop-${{ github.run_id }}-${{ github.run_number }}
      #    path: ./dist/lollipop
